---
title: "UMAP Clustering of CREBBP Ribodepleted RNA-seq"
author: "Jenny Smith"
date: "2/11/21"
output: html_document
---

#Set-up

```{r setup, cache = FALSE, include = FALSE}
require(knitr)
knitr::opts_knit$set(root.dir = file.path(PROJHOME,"2019.12.31_UMAP_Clustering"))
```

```{r}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),
                      tidy=TRUE,
                      fig.align='center',
                      fig.width = 10, fig.height = 10)
options(stringsAsFactors = FALSE,bitmapType = 'cairo', device='x11')
grDevices::X11.options(type='cairo')
table = function (..., useNA = 'ifany') base::table(..., useNA = useNA)
```

```{r message=FALSE}
library(ggplot2)
library(ggrepel)
library(viridis)
library(scales)
library(RColorBrewer)


library(dplyr)
library(magrittr)
library(tibble)
library(tidyr)
library(DeGSEA)

getwd()
```

# Define Functions 

```{r}
scatter_plots_3d <- function(umap_workflow_res, 
                             Group_Column=NULL,
                             Cols=NULL,
                             cc=NULL,
                             add_count=0,
                             blackbg=TRUE,
                             ptsize=4){
  #NOTE: there must be a column for sample IDs called "Sample" in the umap results
  
  
  suppressPackageStartupMessages(library(plotly))
  library(RColorBrewer)
  suppressPackageStartupMessages(library(tidyr))
  library(dplyr)
  
  #re-arrange the umap results dataframe based on the groups of interest
  res <- umap_workflow_res$umap_res %>% 
    arrange(Group_Column)
  
  # Cols <- c("Sample", "Primary.Fusion","Age.in.years","EFS.event.type.ID","Time_point","Overlap.Mutation.Info")
  
  #Create a vector with sample information that will be presented when arrow hovers over the point
  if(!is.null(Cols)){
    if (all(Cols %in% colnames(res))){
      
      info_df <- select(res,one_of(Cols)) %>%
        mutate_if(is.numeric, ~round(., digits=2))
      
      
      info <- gather(info_df,"Col","Value",-one_of("Sample")) %>%
        mutate_at(vars(Value), ~paste0(Col, ": ", .)) %>%
        spread(Col, Value) %>%
        unite("hover_statement",sep="\n",na.rm = F,remove = F)  %>%
        pull(hover_statement, name=Sample)
      
      #re-order the hover information
      info <- info[res$Sample]
      
    }else{
      message(paste("Must have colnames: ", Cols,"in your dataset."))
    }
  }
  
  #define colors for the umap plot based on the number of levels of the groups of interest
  if(is.null(cc)){
    #select the cluster column with the most number of clusters
    groups <- unique(res[[Group_Column]])
    n <- length(groups)
    cc <- c(brewer.pal(n=9,"Set1"),brewer.pal(n=8,"Set2"), brewer.pal(n=9,"Pastel1"))[1:n]
    #adding the names argument is actually the problem??? when you set the name its not mapping the colors to factor levels of the column used for the colors?
    #this used to work but no longer as far as I can tell. Instead colors are simple applied to the order of the factor levels, regardless of being a named vector. 
  }
  
  #whether to set a black backgroup color or not. 
  if(blackbg){
    textcol <- rgb(1,1,1)
    bgcol <- rgb(0,0,0)
  }else{
    textcol <- rgb(0,0,0)
    bgcol <- rgb(1,1,1)
  }
  
  print("this func")
  
  #add a count to the axes if they are too close together
  expand_coords <- function(x,y){ifelse(x>0, x+y, x-y)}
  ranges <- lapply(res[,c("x","y","z")], range)
  ranges <- lapply(ranges, expand_coords,y=add_count)
  
  #plot the umap results
  colorCol <- as.formula(paste("~",Group_Column))
  p <- plot_ly() %>% 
    
    add_trace(data=res,
              x = ~x, y = ~y, z = ~z,
              color = colorCol, 
              colors = cc, 
              type='scatter3d',
              mode='markers',
              text=info,
              hoverinfo='text',
              showlegend=TRUE,
              marker=list(size=ptsize,
                          opacity=0.7),
              inherit = TRUE) %>%
    layout(font = list(color=textcol,
                       size=18),
           scene = list(xaxis = list(title = 'UMAP_1',
                                     color=textcol,
                                     range=ranges$x,
                                     size=18,
                                     backgroundcolor=bgcol,
                                     showbackground=TRUE,
                                     showgrid=TRUE,
                                     gridcolor=textcol,
                                     tickcolor=textcol),
                        yaxis = list(title = 'UMAP_2',
                                     color=textcol,
                                     range=ranges$y,
                                     size=18,
                                     backgroundcolor=bgcol,
                                     showbackground=TRUE,
                                     showgrid=TRUE,
                                     gridcolor=textcol,
                                     tickcolor=textcol),
                        zaxis = list(title = 'UMAP_3',
                                     color=textcol,
                                     range=ranges$z,
                                     size=18,
                                     backgroundcolor=bgcol,
                                     showbackground=TRUE,
                                     showgrid=TRUE,
                                     gridcolor=textcol,
                                     tickcolor=textcol),
                        bgcolor=bgcol),
                        legend=list(font=list(size=18, color=textcol),
                                    itemsizing="trace",
                                    bgcolor=bgcol,
                                    bordercolor=textcol),
                        plot_bgcolor=bgcol,
                        paper_bgcolor=bgcol) %>% 
    config(setBackground=bgcol)
  
  return(p)
}
```


#Read in the Clinical Data

```{r message=FALSE, warning=FALSE}
merged <- readr::read_csv(file.path(CDE,"Merged/TARGET_AML_0531_1031_merged_CDEs_12.09.20.csv"))

merged <- merged %>%
  filter(USI != "Unknown", !is.na(USI))

dim(merged) #2314  145
```

```{r}
sample_info <- read.csv(file.path(TARGET,"SequencingDataMatrix/TARGET_AML_Ribodepleted_Manifest_02.04.21.csv"))


dim(sample_info) #3045   15
head(sample_info)
```

```{r}
CREBBP <- read.csv("CREBBP_list_for_UMAP.csv")

head(CREBBP)
dim(CREBBP) #2313    2
```


#Read in Counts Data

```{r eval=FALSE}
rbd_counts <- readRDS(file.path(PROJHOME,
                                "0000.00.03_ExpressionMatrices/TARGET_AML_MPN_DS_NBM_3044Samples_Ribodepleted_RNAseq_geneLevel_dupGenesRemoved_FractionalCounts.RDS"))


IDmap <- rbd_counts[,c(1:2)]
rbd_counts <- rbd_counts[,-c(1:2)]
rownames(rbd_counts) <- IDmap[,1]

dim(rbd_counts) #51573  3044
head(rbd_counts[,1:5])
```


# Select input samples 

```{r}
include_samples <- sample_info %>% 
  filter(!grepl("FLAGGED|FlowSorted", Time_point)) %>% 
  filter(!grepl("Adult AML (Stirewalt)", Group)) %>% 
  filter(!grepl("AZA", Sample)) %>% 
  
  filter(grepl("^AML$|NBM|CD34_PB", Group), 
         grepl("diagnostic|NBM|CD34_PB", Time_point)) %>%
  
  left_join(., CREBBP, by="USI") %>% 
  mutate_at(vars(CREBBP.alteration), ~case_when(
    is.na(.) ~ Group,
    .=="none" & grepl("KMT2A|CBFB-MYH11|RUNX1-RUNX1T1",AML_Subtype) ~ AML_Subtype,
    .=="none" ~ gsub("none","OtherAML",.),
    TRUE ~ paste0("CREBBP_", .))) %>% 

  left_join(., select(merged,-one_of(c("Protocol","Primary.CNV","Additional.Fusions.CNV",
                                       "Primary.Fusion","Group","Reg."))),
            by="USI") %>% 
  
  as.data.frame() %>%
  set_rownames(.$Sample)



# head(include_samples)
dim(include_samples) # 1616  159
```

```{r}
# table(include_samples$AML_Subtype)
table(include_samples$CREBBP.alteration)
```


#Colors for Plotting

```{r fig.height=2}
colors37 = c("#466791","#60bf37","#953ada","#4fbe6c","#ce49d3","#a7b43d","#5a51dc","#d49f36","#552095","#507f2d","#db37aa","#84b67c","#a06fda","#df462a","#5b83db","#c76c2d","#4f49a3","#82702d","#dd6bbb","#334c22","#d83979","#55baad","#dc4555","#62aad3","#8c3025","#417d61","#862977","#bba672","#403367","#da8a6d","#a79cd4","#71482c","#c689d0","#6b2940","#d593a7","#895c8b","#bd5975")
# barplot(rep(1,37), col=colors37, names.arg = colors37, las=2)
```


# Recolor UMAP Projection 

```{r}
umap_cebpa <- readRDS("Results/Dx_AMLonly_forCEBPA_PCAselect_sg6816/TARGET_AML_sg6818_UMAP_CEBPA_Results.RDS")
```

```{r}
umap_res_recolor <- umap_cebpa$umap_res %>% 
  select(Sample, x:z) %>% 
  left_join(., include_samples, by="Sample") %>% 
  set_rownames(.$Sample)

# umap_res_recolor
table(umap_res_recolor$CREBBP.alteration)

umap_CREBBP <- umap_cebpa
umap_CREBBP$umap_res <- umap_res_recolor
```

```{r fig.height=5, fig.width=10}
Cols <- c( "CREBBP.alteration", "Group", "Tissue" , "Protocol", "Batch")
df <- umap_res_recolor %>% 
  select(all_of(Cols)) 

cc <- colorCodes_aheatmap(df=df)


par(mar=c(10,10,10,10))
barplot(rep(1, length(cc$CREBBP.alteration)),col=cc$CREBBP.alteration, las=2, names.arg = names(cc$CREBBP.alteration))
```


### 3D Plot.ly 

```{r message=FALSE}
library(plotly)
```

```{r}
scatter3d <- scatter_plots_3d(umap_workflow_res = umap_CREBBP, 
                              Group_Column = "CREBBP.alteration",
                              Cols = c("Sample","Primary.Fusion","Primary.CNV","Age.in.years","Overlap.Mutation.Info","EFS.event.type.ID"),
                              cc = cc$CREBBP.alteration,
                              blackbg = TRUE,
                              ptsize = 3)
```

```{r}
dplyr::filter(umap_CREBBP$umap_res, grepl("PAXDXW|PAXCKK", USI))
```


```{r fig.height=10, fig.width=10}
scatter3d
```

```{r}
bgcol <- rgb(0,0,0)
htmlwidgets::saveWidget(as_widget(scatter3d),
                        "TARGET_AML_CREBBP_3Dscatter.html",
                        selfcontained = TRUE,
                        background = bgcol,
                        knitrOptions = list(dpi=1200, 
                                            fig.height = 15,
                                            fig.width=15,
                                            out.width=15, 
                                            out.height=15))
```


# UMAP Workflow from Counts

# Subset Counts 

```{r}
keep <- rowSums(rbd_counts >= 10) >= min(table(include_samples$AML_Subtype)) #minimun number of samples in AML_Subtype
in_counts <- as.matrix(rbd_counts[keep, include_samples$Sample]) 

dim(in_counts) #32258  2176
head(in_counts[,1:5])

# write.csv(in_counts,"TARGET_AML_dx_rlps_NBM_fractional_counts.csv")
```

```{r eval=FALSE}
sample_total <- apply(in_counts, 2, sum)
geomean <- exp(mean(log(sample_total)))
sf <- sample_total/geomean
sf.scaled <- t(t(in_counts)/sf)

dim(sf.scaled)
```


## TF-IDF 

```{r eval=FALSE}

TFIDF <-  seqGlue::tf_idf_transform(sf.scaled)
TFIDF <- as.matrix(TFIDF)

head(TFIDF[,1:5])
dim(TFIDF) #31241  2017
range(TFIDF) #-0.9856885  0.9822756
```


## Input Feature selection 



```{r message=FALSE, eval=FALSE}
library(DelayedArray)
# Mean vs Dispersion Feature Selection 
disp_trend_obj <- seqGlue::calc_dispersion(sf.scaled, 
                                  removeOutliers = TRUE) #removes outlier 

input_genes <- seqGlue::get_selected_genes(seqGlue::select_genes(disp_trend_obj, top_n=NULL))
length(input_genes)  #6634
```

```{r eval=FALSE}
pca_res <- run_jackstraw(TFIDF_Matrix = log2(sf.scaled+1)[input_genes,])


str(pca_res) 
length(pca_res$input_features)
```


## Run the workflow

```{r eval=FALSE}
#columns to use for plotting
Cols <- c("AML_Subtype", "Group","Time_point", "Tissue", "Protocol", "Batch")

#n_neighbors:  Larger values result in more global views of the manifold, while smaller values result in more local data being preserved.

# min_dist: Smaller values will result in a more clustered/clumped embedding where nearby points on the manifold are drawn closer together, while larger values will result on a more even dispersal of points.

CREBBP_umap <- UMAP_workflow(TFIDF_Matrix = TFIDF,
                              input_features = input_genes,
                              samples_vector = pull(include_samples,Sample), 
                              sample_info_df = include_samples, 
                              cc=cc, 
                              min_dist = 0.00125,
                              n_neighbors=27,
                              k2=15,res2=0.01,
                              scale_data=FALSE,
                              Columns_for_Plots = Cols,
                              addl_color_vector = colors37)
```





#Session Information

```{r}
sessionInfo()
```

